- name: Create VPC on AWS
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Create VPC
      amazon.aws.ec2_vpc_net:
        name: "my-ansible-vpc"
        cidr_block: "10.0.0.0/16"
        region: "us-east-1"
        state: present
      register: vpc

- name: Create Subnet on AWS
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Create Subnet
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: "10.0.1.0/24"
        region: "us-east-1"
        state: present
      register: subnet

- name: Create IGW on AWS
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Create IGW
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{ vpc.vpc.id }}"
        region: "us-east-1"
        state: present
      register: igw