- name: Create VPC on AWS
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Create VPC
      amazon.aws.ec2_vpc_net:
        name: "my-ansible-vpc"
        cidr_block: "10.0.0.0/16"
        region: "us-east-1"
        state: present
      register: vpc