---
vpc_name: "my-project-vpc"
network: "10.0.0.0/16"
aws_region: "eu-central-1"
zone: "eu-central-1"
subnet_cidr: "10.0.1.0/24"
subnet: "eu-central-1a"
server_name: "my-project-server"
env: "production"
aws_ubuntu_ami: "ami-0d4a2f1c20fcc71cb"
Server_type: "t2.micro"
keypair: "ProjectDev2"
server_volume_size: 20 # in GB
docker_user: "shaharbaron"
docker_token: "dckr_pat_bDi8RTX3-tNNC4evf3dII1UV-xE"
# vpc_name: "my-ansible-vpc"
# vpc_cidr_block: "10.0.0.0/16"
# subnet_cidr: "10.0.1.0/24"
# aws_region: "us-east-1"
# public_ip: "176.228.223.102"
# aws_ami_id: "ami-0ebfd941bbafe70c6"
# ec2_instance_type: "t2.micro"
# keypair: "my-ansible-key"
# aws_region: "us-east-1"
vpc_id: vpc-00f7c43f9867dd034
subnet_id: subnet-0029c74e14fcc8845
igw_id: igw-0be873d0c65500241
server_ip: 18.195.64.148
server_id: i-0ece02b1cd1ad6c04
