name: upload my image to DockerHub

on:
  push:
    branches: [main]

jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build
        run: docker build . --tag ${{ secrets.DOCKER_USER }}/projectdev:latest

      - name: Push to Docker Hub
        run: docker push ${{ secrets.DOCKER_USER }}/projectdev:latest

  deploy:
    needs: docker_build
    runs-on: ubuntu-latest
    steps:
      - name: deploy site
        uses: actions/checkout@v4
        # with:
        #   host: ${{ secrets.HOST }}
        #   username: ${{ secrets.USER }}
        #   key: ${{ secrets.SSH_KEY }}
        #   port: ${{ secrets.PORT }}
        #   script_stop: true
        #   script: |
        #     cd /opt/app 
        #     sudo docker compose pull && sudo docker compose up -d --force-recreate

            