name: upload my image to DockerHub

on:
  push:
    branches: [ main ]
jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build
        run: docker build . --tag ${{ secrets.DOCKER_USERNAME }} /projectdev:latest

      - name: Push to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }} /projectdev:latest
