name: Upload My Image to DockerHub

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build --tag project_dev:latest . 

      - name: Run Docker container
        run: docker run -d --name app -p 80:80 project_dev:latest

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Chromium browser
        run: sudo apt-get install -y chromium-browser

      - name: Install the necessary Python packages
        run: pip install requests webdriver_manager selenium pytest

      - name: Run the PytTest script
        run: pytest selenium_test/test_memory.py -rA
